# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20181203_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_recommend',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_show',
        ),
    ]
